language: python

python:
  - 3.6

before_install:
  - python -m pip install pytest-cov

install:
  - python -m pip install .

script:
  - pylint --rcfile .pylintrc dof_discord_bot tests/integration_tests setup.py
  - pydocstyle --config .pydocstylerc
  - pytest --cov=dof_discord_bot